npm:
  publish: false
hooks:
  after:bump:
    - node scripts/set-extension-version.js ${version}
    - pnpm run package:firefox
  after:release: node scripts/clean-firefox-artifacts.js
git:
  requireCleanWorkingDir: false
github:
  assets:
    - zips/tinder-autopilot-firefox-v*.zip
    - zips/tinder-autopilot-firefox-source-v*.zip
  release: true
