name: deploy release and notes / change logs

on:
  push:
    branches: main
    tags:
      - '[0-9]+.*'

permissions:
  contents: write  # Explicitamente dando permissão de escrita

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v3

      - name: config git user
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Minor version for each merge
        id: tagger
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          BRANCH_HISTORY: compare

      - name: echo new tag
        run: |
          echo "The next tag version will be: ${{ steps.tagger.outputs.new_tag }}"

      - name: echo tag
        run: |
          echo "The current tag is: ${{ steps.tagger.outputs.tag }}"

      - name: echo part
        run: |
          echo "The version increment was: ${{ steps.tagger.outputs.part }}"

      # Adicione seu build aqui

      - name: Generate release notes
        id: release_notes
        run: |
          notes=$(git log --oneline --decorate --no-merges "${{ steps.tagger.outputs.tag }}..${{ steps.tagger.outputs.new_tag }}")
          echo "::set-output name=notes::${notes}"

      - name: 'Generate tag and create release'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tagger.outputs.new_tag }}
          release_name: Release ${{ steps.tagger.outputs.new_tag }}
          body: ${{ steps.release_notes.outputs.notes }}
          draft: false

      - name: 'Generate changelog and create release'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: '${{ steps.tagger.outputs.new_tag }}'
          prerelease: false
          title: 'Last build: ${{ steps.tagger.outputs.new_tag }}'
          files: |
            *
